# MatheBuddy - a gamified app for higher math
# (c) 2022-2024 by TH Koeln
# Author: Andreas Schwenk contact@compiler-construction.com
# Funded by: FREIRAUM 2022, Stiftung Innovation in der Hochschullehre
# License: GPL-3.0-or-later

name: mathebuddy
description: MatheBuddy - a gamified app for higher math

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.3+14 # must increment version + version code

environment:
  sdk: ">=2.19.2 <3.0.0"
  # TODO: remove pre as soon as 3.13.0 is public available
  #       beta version is currently required for vscode plugin
  #       (required for setting nonce)
  flutter: ">=3.13.0-0.1.pre <10.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  universal_html: ^2.0.9
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  tex: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.2
  http: ^1.1.0
  platform_detector: ^0.2.0
  audioplayers: ^6.0.0 # TODO: must install dependencies for non-macOS desktop app
  collection: ^1.18.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

  assets:
    - assets/img/logo.png
    - assets/img/logo-android-foreground.png
    - assets/img/logo-white-bg.png
    - assets/img/logo-appstore.png
    - assets/img/logoSmall.png
    - assets/img/logo-large-en.png
    - assets/img/logo-large-de.png
    - assets/img/logo-large-no-text.png
    - assets/img/background.jpg
    - assets/bundle-alpha.json
    - assets/bundle-debug.json
    - assets/bundle-smoke.json
    - assets/bundle-websim.json
    - assets/bundle-bochum.json
    - assets/img/logo-institutes.png
    - assets/img/go.svg
    - assets/sfx/pass.wav
    - assets/sfx/fail.wav

# update via $flutter pub get && flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo-appstore.png"
  image_path_android: "assets/img/logo-white-bg.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/logo-android-foreground.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/img/logo-appstore.png"
    background_color: "#ffffff"
    theme_color: "#aa322c"
  windows:
    generate: true
    image_path: "assets/img/logo-appstore.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/logo-appstore.png"
