# mathe:buddy - a gamified app for higher math
# (c) 2022-2023 by TH Koeln
# Author: Andreas Schwenk contact@compiler-construction.com
# Funded by: FREIRAUM 2022, Stiftung Innovation in der Hochschullehre
# License: GPL-3.0-or-later

name: mathebuddy
description: mathe:buddy - a gamified app for higher math

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  universal_html: ^2.0.9
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.2
  tex: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bundle-test.json
    - assets/img/logo.png
    - assets/img/logoSmall.png
    - assets/img/logo-large-en.png
    - assets/img/logo-large-de.png
