name: mathebuddy_bundler
version: 0.0.1
description: Offline course bundler
homepage: https://mathebuddy.github.io/mathebuddy/
repository: https://github.com/mathebuddy/mathebuddy

environment:
  sdk: ">=3.0.0"

dependencies:
  slex: ^0.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
